### PR TITLE
Added secure tokens description

### PR DESCRIPTION
**Pull request by Marketionist**
**This pull request updates services.rst to describe secure tokens usage in .travis.yml**

### CODE REVIEW

**Comment by intellectronica** [comment]
:+1:

**Comment by FinalAngel** [comment]
@Marketionist please wait for merges until you have a go from either me or vadim sometimes. The problem here is, that you need to open the PR against `develop`. As master is a release branch.

**Comment by intellectronica** [comment]
Sorry, I should have spotted this.

It's OK to land though if you get a +1 from anyone in the technical team, and if we discover a problem later on we can just ... fix it :)

**Comment by FinalAngel** [comment]
@intellectronica while this is true for most of our projects, we have some exceptions in place for this boilerplate and django CMS in general. This PR is not critical so It's fine this time. I gently refer to the contribution guidelines: https://aldryn-boilerplate-bootstrap3.readthedocs.org/en/latest/contribution/index.html

**Comment by mkoistinen** [comment]
@Marketionist While this is great, can we also make it a practice to label these token lines with comments in the .travis.yml files themselves? The reason being that there is nothing to distinguish one from another and if someone should have to add more tokens for some future reason, things will get really confusing.

**Comment by Marketionist** [comment]
@mkoistinen Done - see https://github.com/aldryn/aldryn-events/pull/141, https://github.com/aldryn/aldryn-newsblog/pull/282 and https://github.com/aldryn/aldryn-faq/pull/119

**Pull request merged**
